### PR TITLE
Use new wiringX to support RPI2

### PR DESCRIPTION
**Pull request by bjornhij**

### CODE REVIEW

**Comment by sweetpi** [comment]
Did you test the binary on the rpi1(armv6 ovs armv7) ?

**Comment by bjornhij** [comment]
No, only tested on the rpi2.

**Comment by bjornhij** [comment]
Just tried on a model A, and doesnt work..

pi@raspberrypi ~ $ ./vhduino
Illegal instruction

I can compile again, but do not know which compiler options to use.

**Comment by bjornhij** [comment]
pi@raspberrypi ~ $ file vhduino
vhduino: ELF 32-bit LSB executable, ARM, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=0xa5688e5a8734d9ec4ccbe9132b485dcc0c1d4d16, not stripped

**Comment by sweetpi** [comment]
Best is compile on rpi1 then it should work on both.

**Pull request merged**
